// <auto-generated />
using System;
using FWT.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FWT.Database.Migrations
{
    [DbContext(typeof(TelegramDatabaseContext))]
    partial class TelegramDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FWT.Core.Entities.TelegramSession", b =>
                {
                    b.Property<string>("HashId");

                    b.Property<byte[]>("Session")
                        .IsRequired();

                    b.HasKey("HashId");

                    b.ToTable("TelegramSession");
                });
#pragma warning restore 612, 618
        }
    }
}
