// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace FWTL.Database.Migrations
{
    [DbContext(typeof(TelegramDatabaseContext))]
    [Migration("20181108102121_Init")]
    public partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FWT.Core.Entities.TelegramSession", b =>
                {
                    b.Property<string>("HashId");

                    b.Property<byte[]>("Session")
                        .IsRequired();

                    b.HasKey("HashId");

                    b.ToTable("TelegramSession");
                });
        }
    }
}
